version: "3.7"
services:
  mongodb:
    # Сервис MongoDB
    image: mongo:latest # Используем образ MongoDB
    restart: always # Всегда перезапускать контейнер в случае ошибки
    environment:
      MONGO_INITDB_ROOT_USERNAME: root # Имя пользователя по умолчанию
      MONGO_INITDB_ROOT_PASSWORD: rootpassword # Пароль пользователя по умолчанию
      MONGODB_DATABASE: tc
      MONGODB_HOSTNAME: mongodb
      TELEGRAM_TOKEN: "5405385673:AAFvJDIlR4BqQmnXDBGS8XOzEGSpVmE1w84"

    ports:
      - 127.0.0.1:22000:27020 # Проброс порта: локальный порт:27020 -> порт в контейнере:27020
    volumes:
      - mongodb_data:/data/db # Монтируем том для хранения данных MongoDB
  evo_telebot:
    # Сервис evo_telebot
    platform: linux/amd64
    build: . # Сборка контейнера из текущего каталога
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGODB_DATABASE: tc
      MONGODB_HOSTNAME: mongodb
      TELEGRAM_TOKEN: "5405385673:AAFvJDIlR4BqQmnXDBGS8XOzEGSpVmE1w84"

    volumes:
      - ./app:/home/nonroot/app # Монтирование кода приложения в контейнер
    #    volumes:
    #      - ./:/app
    command: sh -c "poetry run python3 bot/__init__.py" # Команда для запуска бота

    depends_on:
      - mongodb # Зависимость: ждем, пока MongoDB будет доступна
  evo_telebot_sync:
    # Сервис evo_telebot_sync
    platform: linux/amd64
    build: .
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGODB_DATABASE: tc
      MONGODB_HOSTNAME: mongodb
      TELEGRAM_TOKEN: "5405385673:AAFvJDIlR4BqQmnXDBGS8XOzEGSpVmE1w84"

    volumes:
      - ./app:/home/nonroot/app # Монтирование кода синхронизации в контейнер
    #    volumes:
    #      - ./:/app
    # command: sh -c "poetry run python3 evotor/sync.py" # Команда для запуска синхронизации

#    depends_on:
#      - mongodb    -

volumes:
  mongodb_data: # Том для MongoDB, используется для сохранения данных
