version: "3.7"
services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 127.0.0.1:27020:27020
    volumes:
      - mongodb_data:/data/db
  evo_telebot_tc:
    platform: linux/amd64
    build: .
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - ./app:/home/nonroot/app
#    volumes:
#      - ./:/app
    command:
      sh -c "poetry run python3 bot/__init__.py"

    depends_on:
      - mongodb
  evo_telebot_sync:
    platform: linux/amd64
    build: .
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - ./app:/home/nonroot/app
    #    volumes:
    #      - ./:/app
    command:
      sh -c "poetry run python3 evotor/sync.py"

#    depends_on:
#      - mongodb    -

volumes:
  mongodb_data:
